"""remove sizing_unit from delivery_orders

Revision ID: 0a7334562d4b
Revises: 620ce688e5d2
Create Date: 2026-03-27 10:38:20.892818

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0a7334562d4b'
down_revision = '620ce688e5d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_orders', schema=None) as batch_op:
        batch_op.drop_column('sizing_unit')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sizing_unit', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True))

    # ### end Alembic commands ###
