"""remove half_meter from delivery_details

Revision ID: 620ce688e5d2
Revises: 
Create Date: 2026-03-27 10:32:18.706319

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '620ce688e5d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = [c['name'] for c in inspector.get_columns('delivery_details')]
    if 'half_meter' in columns:
        with op.batch_alter_table('delivery_details', schema=None) as batch_op:
            batch_op.drop_column('half_meter')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('half_meter', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True))

    # ### end Alembic commands ###
