"""add incoming_source

Revision ID: 8338663e2e63
Revises: a73ea8a26212
Create Date: 2026-04-08 16:22:59.218569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8338663e2e63'
down_revision = 'a73ea8a26212'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yarn_consumptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('incoming_source', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yarn_consumptions', schema=None) as batch_op:
        batch_op.drop_column('incoming_source')

    # ### end Alembic commands ###
