"""add yarn_type to production_orders

Revision ID: 9271dc924066
Revises: 0a7334562d4b
Create Date: 2026-03-27 13:21:52.126528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9271dc924066'
down_revision = '0a7334562d4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('yarn_type', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_orders', schema=None) as batch_op:
        batch_op.drop_column('yarn_type')

    # ### end Alembic commands ###
