"""add note to material_receives

Revision ID: a73ea8a26212
Revises: 892f3f8bb1e3
Create Date: 2026-03-30 13:42:07.524060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a73ea8a26212'
down_revision = '892f3f8bb1e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material_receives', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material_receives', schema=None) as batch_op:
        batch_op.drop_column('note')

    # ### end Alembic commands ###
