"""wage redesign and cleanup

Revision ID: d0319da606a0
Revises: 8338663e2e63
Create Date: 2026-04-12 13:49:55.213385

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd0319da606a0'
down_revision = '8338663e2e63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('position', sa.String(length=50), nullable=False),
    sa.Column('base_salary', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('rent_subsidy', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wage_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('gross_wage', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('rest_days', sa.Integer(), nullable=True),
    sa.Column('deduction', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('net_wage', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'year', 'month', name='uq_emp_year_month')
    )
    op.drop_table('warping_wages')
    op.drop_table('dyeing_wages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dyeing_wages',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('wage_month', mysql.VARCHAR(length=7), nullable=False),
    sa.Column('employee_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('base_salary', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('attendance_days', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('overtime', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('deduction', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('net_salary', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('remark', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('warping_wages',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('wage_date', sa.DATE(), nullable=False),
    sa.Column('employee_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('amount', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('remark', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('wage_records')
    op.drop_table('employees')
    # ### end Alembic commands ###
